name: Continuous Deploy # action名称

on: # 在push代码的时候运行此action
  push:
    branches:
      - main
      - master

jobs:
  auto_deploy_job:
    name: build-deploy

    runs-on: ubuntu-latest # 运行环境，最新ubuntu

    steps:
      - name: Checkout # check out the repository
        uses: actions/checkout@v2 # 这里使用了github官方提供的action,checkout项目到虚拟机上

      - name: Install Dependencies # 安装依赖
        run: yarn

      - name: Build # 构建
        run: yarn build-prod

      - name: Clean remote folder # 删除远程的代码
        uses: garygrossgarten/github-action-ssh@master # 使用第三方action 远程执行命令
        with:
          command: rm -rf /root/project/vue-admin/dist
          username: root
          host: ${{ secrets.SERVER_IP }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY}}

      - name: Upload build file to server # 部署
        uses: appleboy/scp-action@master # 使用第三方action 上传静态文件到服务器
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: 'dist'
          target: '/root/project/vue-admin' # 代码部署路径

      - name: Nginx reload # 重启nginx
        uses: garygrossgarten/github-action-ssh@master # 使用第三方action 远程执行命令
        with:
          command: nginx -s reload
          username: root
          host: ${{ secrets.SERVER_IP }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
