name: Continuous Deploy # action名称

on: # 在push代码的时候运行此action
  push:
    branches:
      - main
      - master

jobs:
  auto_deploy_job:
    name: build-deploy

    runs-on: ubuntu-latest # 运行环境，最新ubuntu

    steps:
      - name: Nginx reload # 重启nginx
        uses: garygrossgarten/github-action-ssh@release # 使用第三方action 远程执行命令
        with:
          command: nginx -s reload
          username: root
          env:
            host: ${{ secrets.SERVER_IP }}
            privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
